// frontend/src/routes/Register.svelte
<script lang="ts">
  import { authApi } from '../lib/api/auth';
  import { toast } from '../lib/stores/toast.svelte';
  import Input from '../lib/components/ui/Input.svelte';
  import Button from '../lib/components/ui/Button.svelte';
  import Spinner from '../lib/components/ui/Spinner.svelte';
  import { UserPlus } from '@lucide/svelte';

  let username = $state('');
  let password = $state('');
  let confirmPassword = $state('');
  let isSubmitting = $state(false);
  let errorMessage = $state('');

  async function handleRegister(e: SubmitEvent) {
    e.preventDefault();
    if (!username.trim() || !password.trim() || !confirmPassword.trim()) {
      errorMessage = 'Semua field wajib diisi.';
      return;
    }

    if (password !== confirmPassword) {
      errorMessage = 'Konfirmasi password tidak cocok dengan password.';
      return;
    }

    if (password.length < 3) {
      errorMessage = 'Password minimal harus 3 karakter.';
      return;
    }

    errorMessage = '';
    isSubmitting = true;

    try {
      await authApi.register({
        username: username.trim(),
        password: password.trim(),
        confirmPassword: confirmPassword.trim(),
      });
      toast.success('Pendaftaran berhasil! Silakan masuk ke akun Anda.');
      window.location.hash = '#/login';
    } catch (err: any) {
      errorMessage = err.message || 'Pendaftaran gagal. Silakan coba lagi.';
      toast.error(errorMessage);
    } finally {
      isSubmitting = false;
    }
  }
</script>

<div class="min-h-[75vh] flex items-center justify-center px-4 py-12">
  <div class="w-full max-w-md bg-white border border-neutral-300 rounded-xl p-8 shadow-sm space-y-6">
    <div class="text-center space-y-1.5">
      <div class="w-12 h-12 mx-auto rounded-xl bg-neutral-900 text-white flex items-center justify-center">
        <UserPlus size={22} />
      </div>
      <h2 class="text-2xl font-bold text-neutral-950">Daftar Akun Baru</h2>
      <p class="text-xs text-neutral-500">Daftarkan akun siswa untuk mulai belajar dan berlatih</p>
    </div>

    {#if errorMessage}
      <div class="p-3 bg-neutral-100 border border-neutral-300 rounded-lg text-xs font-medium text-neutral-900 leading-normal">
        {errorMessage}
      </div>
    {/if}

    <form onsubmit={handleRegister} class="space-y-4">
      <Input
        id="username"
        label="Username"
        placeholder="Pilih username unik"
        bind:value={username}
        required
      />

      <Input
        id="password"
        type="password"
        label="Password"
        placeholder="Minimal 3 karakter"
        bind:value={password}
        required
      />

      <Input
        id="confirmPassword"
        type="password"
        label="Konfirmasi Password"
        placeholder="Ulangi password di atas"
        bind:value={confirmPassword}
        required
      />

      <Button
        type="submit"
        variant="primary"
        class="w-full py-2.5"
        disabled={isSubmitting}
      >
        {#if isSubmitting}
          <Spinner size="sm" class="border-t-white" />
          <span>Mendaftarkan Akun...</span>
        {:else}
          <span>Daftar Sekarang</span>
        {/if}
      </Button>
    </form>

    <div class="text-center pt-2 border-t border-neutral-200">
      <p class="text-xs text-neutral-600">
        Sudah memiliki akun?
        <a href="#/login" class="font-semibold text-neutral-950 hover:underline">
          Masuk di sini
        </a>
      </p>
    </div>
  </div>
</div>

// frontend-react/src/pages/Register.tsx
import { useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useNavigate } from '@tanstack/react-router'
import { UserPlus } from 'lucide-react'
import { authApi } from '../lib/api/auth'
import { toast } from '../lib/stores/toast'
import { Button } from '../lib/components/ui/Button'
import { Input } from '../lib/components/ui/Input'
import { Spinner } from '../lib/components/ui/Spinner'

export function RegisterPage() {
  const navigate = useNavigate()

  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')

  async function handleRegister(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!username.trim() || !password.trim() || !confirmPassword.trim()) {
      setErrorMessage('Semua field wajib diisi.')
      return
    }

    if (password !== confirmPassword) {
      setErrorMessage('Konfirmasi password tidak cocok dengan password.')
      return
    }

    if (password.length < 3) {
      setErrorMessage('Password minimal harus 3 karakter.')
      return
    }

    setErrorMessage('')
    setIsSubmitting(true)

    try {
      await authApi.register({
        username: username.trim(),
        password: password.trim(),
        confirmPassword: confirmPassword.trim(),
      })
      toast.success('Pendaftaran berhasil! Silakan masuk ke akun Anda.')
      await navigate({ to: '/login' })
    } catch (error: any) {
      const message = error.message || 'Pendaftaran gagal. Silakan coba lagi.'
      setErrorMessage(message)
      toast.error(message)
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <div className="min-h-[75vh] flex items-center justify-center px-4 py-12">
      <div className="w-full max-w-md bg-white border border-neutral-300 rounded-xl p-8 shadow-sm space-y-6">
        <div className="text-center space-y-1.5">
          <div className="w-12 h-12 mx-auto rounded-xl bg-neutral-900 text-white flex items-center justify-center">
            <UserPlus size={22} />
          </div>
          <h2 className="text-2xl font-bold text-neutral-950">Daftar Akun Baru</h2>
          <p className="text-xs text-neutral-500">
            Daftarkan akun siswa untuk mulai belajar dan berlatih
          </p>
        </div>

        {errorMessage ? (
          <div className="p-3 bg-neutral-100 border border-neutral-300 rounded-lg text-xs font-medium text-neutral-900 leading-normal">
            {errorMessage}
          </div>
        ) : null}

        <form onSubmit={handleRegister} className="space-y-4">
          <Input
            id="username"
            label="Username"
            placeholder="Pilih username unik"
            value={username}
            onValueChange={setUsername}
            required
          />

          <Input
            id="password"
            type="password"
            label="Password"
            placeholder="Minimal 3 karakter"
            value={password}
            onValueChange={setPassword}
            required
          />

          <Input
            id="confirmPassword"
            type="password"
            label="Konfirmasi Password"
            placeholder="Ulangi password di atas"
            value={confirmPassword}
            onValueChange={setConfirmPassword}
            required
          />

          <Button type="submit" variant="primary" className="w-full py-2.5" disabled={isSubmitting}>
            {isSubmitting ? (
              <>
                <Spinner size="sm" className="border-t-white" />
                <span>Mendaftarkan Akun...</span>
              </>
            ) : (
              <span>Daftar Sekarang</span>
            )}
          </Button>
        </form>

        <div className="text-center pt-2 border-t border-neutral-200">
          <p className="text-xs text-neutral-600">
            Sudah memiliki akun?{' '}
            <Link to="/login" preload="intent" className="font-semibold text-neutral-950 hover:underline">
              Masuk di sini
            </Link>
          </p>
        </div>
      </div>
    </div>
  )
}
